[workspace]
publish = true
git_release_enable = true
git_tag_enable = true
changelog_update = true
semver_check = false

[changelog]
header = "# Changelog\n\nAll notable changes to ZenSync will be documented in this file.\n\n"
body = """

## [{{ version }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{{ commit.message | upper_first }}{% endfor %}
{% endfor %}
"""
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^docs", group = "Documentation" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Changed" },
  { message = "^chore", skip = true },
  { message = "^test", skip = true },
  { message = "^ci", skip = true },
]
